-- Backfills 9 old (June/August) Stock Log rows that were skipped during
-- the original migration because their Type column was blank or wrong
-- in the source sheet. History-only — balances are unaffected (they're
-- always set from the September ground-truth snapshot, not replayed).
alter table products add column if not exists import_key text;
update products set import_key = 'ռուլոն սպիտակ|facial tissue|126.0|2.0|14.0' where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(126.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 4516.0, '2026-06-04', 'Auto: receiving 1780597801715 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "—")' from products where import_key = 'ռուլոն սպիտակ|facial tissue|126.0|2.0|14.0';
update products set import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0' where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 1040.0, '2026-06-04', 'Auto: receiving 1780601054751 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "—")' from products where import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0';
update products set import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0' where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 10000.0, '2026-06-04', 'Auto: receiving 1780606989287 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "—")' from products where import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0';
update products set import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0' where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 100010.0, '2026-06-04', 'Auto: receiving 1780608267553 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "—")' from products where import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0';
update products set import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0' where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 1040.0, '2026-06-04', 'Auto: receiving 1780608586922 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "—")' from products where import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0';
update products set import_key = 'ռուլոն սպիտակ|facial tissue|126.0|2.0|14.0' where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(126.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 4516.0, '2026-06-05', 'Auto: receiving 1780608592431 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "—")' from products where import_key = 'ռուլոն սպիտակ|facial tissue|126.0|2.0|14.0';
update products set import_key = 'ռուլոն սպիտակ|facial tissue|20.0|3.0|14.0' where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(20.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 3084.0, '2026-06-05', 'Auto: receiving 1780689969170 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "—")' from products where import_key = 'ռուլոն սպիտակ|facial tissue|20.0|3.0|14.0';
update products set import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0' where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 1040.0, '2026-06-05', 'Auto: receiving 1780690663337 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "—")' from products where import_key = 'ռուլոն սպիտակ|towels|135.0|1.0|20.0';
update products set import_key = 'ռուլոն սպիտակ|towels|46.0|2.0|20.0' where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(20.0,-1) and import_key is null;
insert into stock_log (product_id, operation, quantity, date, note) select id, 'add', 3090.0, '2026-08-11', 'Auto: receiving 1786101273192 · by Vahe · ⚠️ backfilled (source Type was blank/wrong: originally "Dispenser")' from products where import_key = 'ռուլոն սպիտակ|towels|46.0|2.0|20.0';
alter table products drop column import_key;
-- 9 rows backfilled
