-- ============================================================
-- SoftStock — FINAL BALANCE RESET to ground truth (2026-09-22)
-- Run this LAST, after any stock_log/reservation imports — it
-- overwrites balance directly, so it's immune to the stock_log
-- insert trigger. Safe to re-run any number of times.
-- ============================================================

alter table products add column if not exists import_key text;

update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(18.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 3927.7000000000007 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(18.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 3124.5 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(20.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 18310.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(20.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 2985.5 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 394.80000000000007 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(18.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(15.0,-1);
update products set balance = 3235.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 15734.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 4561.9 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(21.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 845.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 9601.6 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(27.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(19.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(28.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(28.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 494.3 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(28.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 5871.5 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 428.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 1896.8 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(15.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 4545.2 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 1620.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(32.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(15.0,-1);
update products set balance = 6460.299999999999 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 4753.2 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 320.0 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 856.1 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(15.0,-1);
update products set balance = 1269.6000000000004 where name = 'Ռուլոն սպիտակ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(36.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 9699.3 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(37.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(37.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(15.0,-1);
update products set balance = 3149.8 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(37.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(15.0,-1);
update products set balance = 405.7 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(25.0,-1);
update products set balance = 124.6 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 1282.9 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 97.8 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 975.8 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 468.8 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 3051.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(42.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(30.0,-1);
update products set balance = 5900.5 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(42.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 3907.6 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(42.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(18.0,-1);
update products set balance = 820.0 where name = 'Ռուլոն սպիտակ' and type = 'Dispenser' and coalesce(width_cm,-1)=coalesce(42.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(19.0,-1);
update products set balance = 11664.0 where name = 'Ռուլոն սպիտակ' and type = 'Dispenser' and coalesce(width_cm,-1)=coalesce(42.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 5597.0 where name = 'Ռուլոն սպիտակ' and type = 'Dispenser' and coalesce(width_cm,-1)=coalesce(42.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(22.0,-1);
update products set balance = 271.9 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(42.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(NULL,-1);
update products set balance = 13260.4 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(44.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 913.3 where name = 'Ռուլոն սպիտակ' and type = 'Dispenser' and coalesce(width_cm,-1)=coalesce(44.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(19.0,-1);
update products set balance = 9433.0 where name = 'Ռուլոն սպիտակ' and type = 'Dispenser' and coalesce(width_cm,-1)=coalesce(44.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 1547.7 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(45.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 2210.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 5955.7 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(25.0,-1);
update products set balance = 10363.3 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 2094.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 2234.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(15.0,-1);
update products set balance = 9975.3 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 2001.9 where name = 'Ռուլոն սպիտակ մ.' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(48.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(25.0,-1);
update products set balance = 4163.2 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(48.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 4173.3 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(48.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 6201.7 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(48.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 165.7 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(25.0,-1);
update products set balance = 1285.8999999999992 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(15.0,-1);
update products set balance = 740.3000000000002 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 2604.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(50.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(40.0,-1);
update products set balance = 390.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(50.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 6675.1 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(55.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 5954.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(55.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 2973.5999999999985 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(60.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 1457.9 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(60.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 5519.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(60.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 8654.2 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(70.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 14587.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(70.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 34238.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(72.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 11950.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(72.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 39165.8 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(80.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 7843.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(80.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 17379.5 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(112.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 3090.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(112.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 8104.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(112.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 12999.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(120.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 11355.5 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(120.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 18723.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(126.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 11359.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(126.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 6493.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 4145.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 4091.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 2677.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 11120.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 4750.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 5090.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 12496.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 306.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն սպիտակ' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 1249.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(140.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 9518.0 where name = 'Ռուլոն սպիտակ' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(140.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 2313.0 where name = 'M-7' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(18.0,-1);
update products set balance = 1611.8 where name = 'M-7' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(18.0,-1);
update products set balance = 4803.0 where name = 'C2' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(140.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 906.0 where name = 'C2' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(140.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(25.0,-1);
update products set balance = 13760.0 where name = 'C23' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 4732.6 where name = 'C2' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(42.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(21.0,-1);
update products set balance = 1154.4 where name = 'Ռուլոն գունավոր' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 632.0 where name = 'Ռուլոն գունավոր' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 9071.0 where name = 'Ռուլոն գունավոր' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(48.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 1850.0 where name = 'Ռուլոն գունավոր' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(55.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 3238.0 where name = 'Ռուլոն գունավոր' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(60.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 1540.0 where name = 'Ռուլոն գունավոր' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(72.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 4358.1 where name = 'Ռուլոն վարդագույն' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 1623.6999999999998 where name = 'Ռուլոն կարմիր' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 531.7 where name = 'Ռուլոն կարմիր' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 112.7 where name = 'Ռուլոն կարմիր' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 139.9 where name = 'Ռուլոն կարմիր' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 361.3 where name = 'Ռուլոն կարմիր' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն կապույտ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն կապույտ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 142.3 where name = 'Ռուլոն բորդո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 1372.6 where name = 'Ռուլոն բորդո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 1092.3 where name = 'Ռուլոն սև' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 157.9 where name = 'Ռուլոն սև' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 5175.0 where name = 'Ռուլոն դեղին' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(126.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 4687.9 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(18.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(19.0,-1);
update products set balance = 3170.3 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 4856.2 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(23.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(19.0,-1);
update products set balance = 3311.0 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 795.0 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 3743.2999999999993 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 493.9 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(19.0,-1);
update products set balance = 2924.0 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(30.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 1439.9 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(33.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 705.3 where name = 'Ռուլոն Էկո' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(37.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 474.4 where name = 'Ռուլոն Էկո' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 3812.3 where name = 'Ռուլոն Էկո' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(48.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 4222.0 where name = 'Ռուլոն Էկո' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 3770.0 where name = 'Ռուլոն Էկո' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 4763.7 where name = 'Ռուլոն Էկո' and type = 'Towels' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=3 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'Ռուլոն Էկո' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 3413.0 where name = 'Ռուլոն Էկո' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(80.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 4061.0 where name = 'Ռուլոն Էկո' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 2849.5 where name = 'Ռուլոն Էկո' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(135.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(16.0,-1);
update products set balance = 0.0 where name = 'M-7' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 0.0 where name = 'M-7' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(40.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(17.0,-1);
update products set balance = 4035.0 where name = 'M-7' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(18.0,-1);
update products set balance = 0.0 where name = 'M-7' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(46.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(20.0,-1);
update products set balance = 0.0 where name = 'M-7' and type = 'Toilet Paper' and coalesce(width_cm,-1)=coalesce(49.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(25.0,-1);
update products set balance = 6558.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(80.0,-1) and ply=4 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 1293.6399999999999 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(14.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(35.0,-1);
update products set balance = 461.0 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(14.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(45.0,-1);
update products set balance = 2640.8000000000006 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(19.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(33.0,-1);
update products set balance = 3854.16 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(19.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(35.0,-1);
update products set balance = 498.1499999999995 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(19.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(40.0,-1);
update products set balance = 485.91 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(19.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(45.0,-1);
update products set balance = 0.0 where name = 'Spunlace Embossed' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(19.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(45.0,-1);
update products set balance = 609.0 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(19.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(50.0,-1);
update products set balance = 1693.0 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(14.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(38.0,-1);
update products set balance = 950.0 where name = 'Spunlace plain' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(13.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(35.0,-1);
update products set balance = 1438.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(37.0,-1) and ply=4 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 2852.0 where name = 'Ռուլոն սպիտակ' and type = 'Facial Tissue' and coalesce(width_cm,-1)=coalesce(72.0,-1) and ply=4 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 0.0 where name = 'БУМАГА-ОСНОВА БС, 14 Г/М2, 1 СЛ., 240 ММ' and type = 'Napkins' and coalesce(width_cm,-1)=coalesce(24.0,-1) and ply=1 and coalesce(gsm,-1)=coalesce(14.0,-1);
update products set balance = 0.0 where name = 'Нетканый материал Спанбейс 20/80 40 гр/м2 формат 190мм' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(19.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(40.0,-1);
update products set balance = 0.0 where name = 'Нетканый материал Спанбейс 20/80 35 гр/м2 формат 140мм' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(14.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(35.0,-1);
update products set balance = 0.0 where name = 'Нетканый материал Спанбейс 20/80 33 гр/м2 формат 190мм' and type = 'Spunlace' and coalesce(width_cm,-1)=coalesce(19.0,-1) and ply=2 and coalesce(gsm,-1)=coalesce(33.0,-1);

alter table products drop column import_key;
-- 172 products reset, total = 643867.6600000004
